### ISSUE TITLE
Figure out how to refresh the data only once every 24hrs to avoid rate limiting

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/CostControl#3]
maybe this will help... not sure
```php
$timefromdatabase = 1489834968;

$dif = time() - $timefromdatabase;

if($dif > 86400)
{
echo 'more than 24 hours';
}else{
 echo 'less than 24 hours';
}
```

https://stackoverflow.com/questions/42875681/php-check-if-a-whole-24-hours-have-passed-with-time

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/229580925-61ee5056-d81c-4757-a7d1-e9a382d3af61.png)

I think we need to use the unix date to work out the 24hrs

![image](https://user-images.githubusercontent.com/10233708/229581001-730e9117-ff1f-41d1-85bf-b3ad171b2fe7.png)

**Comment by creecros** [comment]
Yes, that would be the best route.

**Comment by aljawaid** [comment]
but i still need to load the page to get the updated time right?  i have the date coming from the json, but the php is loaded on page load.... so do i need to save the page load date/time in unix in a metasetting?
